project:
  type: website
  output-dir: docs

website:
  title: "PA470"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ryanzomorrodi/PA470
format:
  html:
    theme: cosmo
    css: styles.css



